@url = http://localhost:4004
@path = authentication
@login = admin:pass

### METADATA
GET {{url}}/{{path}}/$metadata

### GET Users
GET {{url}}/{{path}}/UserSet

### GET isAuthenticated
GET {{url}}/{{path}}/isAuthenticated()
Authorization: Basic {{login}}
