@url = http://localhost:4004
@path = bouldering
@login = admin:pass
### METADATA
GET {{url}}/{{path}}/$metadata
Authorization: Basic {{login}}

########################
######## ROUTES ########
########################

### GET RouteSet
GET {{url}}/{{path}}/RouteSet?$expand=tags($expand=tag),registrations
Authorization: Basic {{login}}

### Get a specific Route
GET {{url}}/{{path}}/RouteSet('{{route1id}}')
Authorization: Basic {{login}}

### POST RouteSet
# @name route1
@route1id = {{route1.response.body.$.ID}}
POST {{url}}/{{path}}/RouteSet
content-Type: application/json
Authorization: Basic {{login}}

{
    "name": "New test route",
    "officialGrade": "Blue",
    "amountOfHolds": 15,
    "active": true,
    "removedAt": null,
    "wallType": "Slab",
    "tags": [
        {"tag_ID": "{{tag1id}}"},
        {"tag_ID": "{{tag2id}}"},
        {"tag_ID": "{{tag3id}}"}
    ]
}

### DELETE a Route
DELETE {{url}}/{{path}}/RouteSet('{{route1id}}')
Authorization: Basic {{login}}

### GET Tags
GET {{url}}/{{path}}/TagSet?$expand=routes
Authorization: Basic {{login}}

########################
######### TAGS #########
########################

### POST a new Tag
# @name tag1
@tag1id = {{tag1.response.body.$.ID}}
POST {{url}}/{{path}}/TagSet
content-Type: application/json
Authorization: Basic {{login}}

{
    "name": "Heelhook",
    "tagText": "Heel Hook"
}


### POST another tag
# @name tag2
@tag2id = {{tag2.response.body.$.ID}}
POST {{url}}/{{path}}/TagSet
content-Type: application/json
Authorization: Basic {{login}}

{
    "name": "ToeHook",
    "tagText": "Toe Hook"
}

### POST a third tag
# @name tag3
@tag3id = {{tag3.response.body.$.ID}}
POST {{url}}/{{path}}/TagSet
content-Type: application/json
Authorization: Basic {{login}}

{
    "name": "Dyno",
    "tagText": "Dyno"
}


### DELETE a Tag
DELETE {{url}}/{{path}}/TagSet('{{tag3id}}')
Authorization: Basic {{login}}

###########################
######## REGISTERS ########
###########################

### GET RegisterSet
GET {{url}}/{{path}}/RegisterSet
Authorization: Basic {{login}}

### POST a new Registration
POST {{url}}/{{path}}/RegisterSet
content-Type: application/json
Authorization: Basic {{login}}

{
    "route_ID": "{{route1id}}",
    "runnerGradeDifficulty": 3,
    "attempts": 2,
    "status": "In Progress"
}